# ===================================================================
# IKEA BILRESA E2489 Dual Button – Matter Edition
# Blueprint Template v1.0.0
# Internal Versioning:
#   schema_version: 1.0.0
#   last_updated: 2025-12-13
#   notes:
#     - Event model based on state_changed of event entities
#     - Press types: multi_press_1, multi_press_2, long_release
#     - Long-press model: Option A (trigger on release only)
# ===================================================================

blueprint:
  name: IKEA BILRESA E2489 Dual Button (Matter)
  description: >
    Template blueprint for handling single press, double press, and long press
    (on release) for the IKEA BILRESA E2489 Matter dual-button remote.
    Uses event entities exposed by Home Assistant for Matter devices.
  domain: automation
  source_url: https://community.home-assistant.io/
  homeassistant:
    min_version: 2025.12.0

  input:
    target_device:
      name: BILRESA Button Device
      description: >
        Select the IKEA BILRESA E2489 device. This blueprint will automatically
        detect the event entities associated with the device.
      selector:
        device:
          filter:
            - manufacturer: IKEA of Sweden

    single_press_action:
      name: Single Press Action
      description: Action to run when a single press (multi_press_1) is detected.
      default: []
      selector:
        action: {}

    double_press_action:
      name: Double Press Action
      description: Action to run when a double press (multi_press_2) is detected.
      default: []
      selector:
        action: {}

    long_press_action:
      name: Long Press Action
      description: >
        Action to run when a long press is completed (long_release).
        This blueprint uses the long-release event as the trigger.
      default: []
      selector:
        action: {}

# ===================================================================
# AUTOMATION LOGIC
# ===================================================================

variables:
  device_id: !input target_device

trigger:
  - platform: state
    entity_id:
      - "{{ expand(device_entities(device_id)) | select('match', '^event\\.') | list }}"
    # No 'to:' filter because event entities use timestamp states

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.event_type == 'multi_press_1' }}
        sequence: !input single_press_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.event_type == 'multi_press_2' }}
        sequence: !input double_press_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.attributes.event_type == 'long_release' }}
        sequence: !input long_press_action

mode: single